### ISSUE TITLE
Activate POS with self hosted RSU

### ISSUE THREAD

**Issue by manasayub** [microsoft/Dynamics365Commerce.InStore#10]
Hi team,

I am stuck with an issue like i have setup self hosted RSU , now i want to login and activate POS so how it will be authenticated? Please note i am using windows 10 and don’t have preconfigured virtual box .

**Comment by lukedgr** [comment]
Hi, self-hosted mode is meant for lightweight CSU development scenarios and currently does not support authenticated APIs. For POS development, please set up a local CSU in [IIS mode](https://github.com/microsoft/Dynamics365Commerce.ScaleUnit/blob/release/9.37/src/ScaleUnitSample/Readme.md#iis-mode).

**Comment by manasayub** [comment]
Can a LcS hosted cloud dev box support same POS APIs for authentication? I mean if we have developed an pos latest extension can we test it on local retail server ? as we previously do with legacy Retail SDK ?
