### ISSUE TITLE
Using unmanaged dll in Hardware Station

### ISSUE THREAD

**Issue by Suhail-Ismail** [microsoft/Dynamics365Commerce.InStore#13]
Is it possible to use unmanaged dll in hardware station?

**Comment by Pikhulya** [comment]
If you meant creating an HS extension interacting with unmanaged code with help of, for instance [UnmanagedFunctionPointerAttribute](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.unmanagedfunctionpointerattribute?view=net-6.0) then, yes, it can be done.
