### ISSUE TITLE
Store Commerce App - Multiple MPOS extensions migration

### ISSUE THREAD

**Issue by KishoreReddyVuppada** [microsoft/Dynamics365Commerce.InStore#14]
1.Currently, in legacy MPOS solution we have multiple POS extensions (with different manifest) which includes localizations features for Italy, France etc. In Independent packaging, extensions.json file is moved to crt trigger GetExtensionPackageDefinitionsRequest.
As per the recording/samples, GetExtensionPackageDefinitionsRequest need to include manifest name (Contoso.StoreCommercePackagingSample) and this extension will load the MPOS packages accordingly. Since, we have multiple manifests in this case, could you please let me know how to proceed with this. (How do we need to add these manifests in crt trigger). I tried to include other extension packages in crt trigger with name matching the manifest of MPOS extension. Looks like extension is not loading the MPOS extension.
                              
2. We can’t create a separate project for each feature/extension, since there are lot of extensions already in this project. As this will create multiple installers and maintenance would be difficult.

3. Also, we have multiple controllers in RS, so we have created/generated multiple custom data service, data entities files. In this new approach, how can we generate these files and consume in MPOS. Do we need to have separate commerce proxy generation project to generate these files?

**Comment by lukedgr** [comment]
1 & 2. For MPOS and Store Commerce we recommend that each extension package and manifest.json should be package and installed separately to fully support independent servicing of extensions. These installers can be scripted to run in sequence to simplify installs, but it provides additional flexibility to only update one extension package if there is a critical update needed. If a single installer is still preferred the best way is to create a single extension package with all of the extensions included please merge the manifest.json files into a single combined extension package.

3. The Retail Server Proxy for POS extensions will be automatically created when the POS extension project references the Commerce Runtime project that contains a Retail Server controller. An example can be found [here](https://github.com/microsoft/Dynamics365Commerce.InStore/blob/release/9.38/src/StoreCommerceSamples/Solutions/GasStationSample/Pos/Contoso.GasStationSample.Pos.csproj) in the Gas Station Sample with the GasPumpsController.
