### ISSUE TITLE
Buttons with action properties not showing Tooltips

### ISSUE THREAD

**Issue by Vekto** [microsoft/Dynamics365Commerce.InStore#17]
a button that has an action attached doesn't show tooltips.. Payment methods are a good example that show this behavior.

in Pos.Controls.js the tooltip is set correctly on lines 17942/17945/17948. but then is cleared by line 17950.

![image](https://user-images.githubusercontent.com/11138147/184410131-b6949a4d-3fb0-4b57-96d9-a575348029e3.png)

Inside the formatedJoin. method if more then 1 element exists the second element will end up in the format call, with a " " format string.

![image](https://user-images.githubusercontent.com/11138147/184411998-506d89a0-4fbb-4ac1-92ab-b8ba5bcc501b.png)

this then returns the " " string from the format call

![image](https://user-images.githubusercontent.com/11138147/184412110-248f9b2a-f131-437f-8da1-132bd42f15d1.png)

**Comment by lukedgr** [comment]
Thank you for reporting this issue. This should be fixed in version 9.37 of Store Commerce (and MPOS).

In the future, please only use this page to report issues related to Commerce customization development. Thanks!
