### ISSUE TITLE
Unable to run complete GasStationSample on IIS hosted local development

### ISSUE THREAD

**Issue by vkommuri2897** [microsoft/Dynamics365Commerce.InStore#19]
Hi,

I am trying to run this sample in IIS hosted local development but Commerce Scale Unit changes are not updated in local CommerceRuntime folder when i compile and run F5 the sample in Visual Studio code. Can you please provide complete steps to run the sample.

**Comment by Pikhulya** [comment]
@lukedgr - FYI.

**Comment by lukedgr** [comment]
Hi @vkommuri2897, thanks for pointing out this gap in this sample. We will update the sample include a Commerce Scale Unit installer in an upcoming release. For now, please modify the sample to create a Commerce Scale Unit installer project referencing the Pos project and the CommerceRuntime project. Then once the installer is built you can install it using the steps outlined in the link below.

https://github.com/microsoft/Dynamics365Commerce.ScaleUnit/blob/release/9.40/src/ScaleUnitSample/Readme.md#debugging-1
