### ISSUE TITLE
Cannot get sample extensions to load

### ISSUE THREAD

**Issue by ahrazusmani** [microsoft/Dynamics365Commerce.InStore#2]
Followed the documentation and was able to successfully build the solution.  Installed the extension package successfully, but no extensions load in the MPOS application.  Event viewer shows the warning:  **Extension package named 'Contoso.Commerce' installed but not configured (no package definition found).**

What am i missing?

**Comment by lukedgr** [comment]
The extension package needs to be configured or MPOS will not load it. To configure the extension package please refer to the documentation below.

https://docs.microsoft.com/en-us/dynamics365/commerce/dev-itpro/pos-extension/pos-extension-basics#configuring-extension-packages

**Comment by Pikhulya** [comment]
@ahrazusmani assuming you are unblocked by following the above recommendations, this issue will be closed, please let us know if you are still blocked.

**Comment by Pikhulya** [comment]
@ahrazusmani as you confirmed in [Yammer](https://www.yammer.com/dynamicsaxfeedbackprograms/threads/1350893062414336) the issue is resolved therefore it is being closed here.
