### ISSUE TITLE
Getting stuck during activation

### ISSUE THREAD

**Issue by Vekto** [microsoft/Dynamics365Commerce.InStore#20]
Seems in .28 providing a bad retail server URL in the beginning will get the activation process stuck. it fails to retrieve the device configuration and won't allow you to start over. Closing re-opening the app doesn't work, it just keeps retrying.

**Comment by Pikhulya** [comment]
Since you didn't outline whether you are using MPOS or Store Commerce or CPOS I will assume that is CPOS. If so - did you try InPrivate/Incognito mode? If that is MPOS/Store Commerce - did you try uninstall and then install again to see if you can proceed providing right Url ?

**Comment by Vekto** [comment]
Sorry about that. It is Store Commerce, an uninstall/re-install was the only way to get it unstuck.
In testing, if I just deactivate a POS, then put in bad URLs without closing and re-opening it handles them fine. But if you put in a bad URL after a fresh start of the app it gets stuck. Doesn't replicate in CPOS and I don't have a MPOS to test against. Replicated on 2 dev environments

**Comment by Pikhulya** [comment]
This has been fixed in 10.0.31.
