### ISSUE TITLE
Retail SDK to Store Commerce migration issues while configuring:

### ISSUE THREAD

**Issue by chmasade** [microsoft/Dynamics365Commerce.InStore#22]
Hello everyone,

Good Day!!!

We are migrating Retail SDK to Store Commerce, and having below queries. 

Request your help here...

1.We like to add multiple projects with single installer, but getting deployment issue as it is deploying only one project (i.e last project in the solution). Is that we are missing something here. Can you please advise?
Issue like while adding multiple project reference in a single pos extension installer, it is deploying only one project in the extension folder of d365.
2.	Can we make the package name as dynamic not hardcoded, which is defined in POS extension package trigger.
Basically, we are mentioning the package name in the defineposextension trigger and the same name in the customization package props file. Is there possibility to make this as dynamic like a configuration in HQ?
3.	Can we use telemetry in store commerce as we use in Retail SDK(POS).
Telemetry:
We are trying to log the information and customization errors in AppInsight of Azure. We are following the link as provided by MS [Log extension events to Application Insights - Commerce | Dynamics 365 | Microsoft Learn](https://learn.microsoft.com/en-us/dynamics365/commerce/dev-itpro/commerce-application-insights)
We are facing issue as we are not able to build the project and getting the configuration error in tsconfig.json file after installation of npm module.

Thanks,
Chaya Masade

**Comment by lukedgr** [comment]
Hi @chmasade , could you please split the questions into separate issues so we can have a dedicated thread on each question?

**Comment by lukedgr** [comment]
closing as this was split into separate issues for each question.
