### ISSUE TITLE
Pivot Control Migration Issues

### ISSUE THREAD

**Issue by zubair1599** [microsoft/Dynamics365Commerce.InStore#23]
We are migrating POS extensions from MPOS to Store Commerce. We found pivot control in 10.0.26 release (https://fix.lcs.dynamics.com/Issue/Details?bugId=659253&dbType=3). Further we tried migrating to new control but view is distorted. Since Pivot items are not generated from control factory, it seems bindings are not working. Overall the view is distorted. If you can provide some sample for pivot control showing some bound data, it will be helpful.

**Comment by lukedgr** [comment]
Hi @zubair1599 , could you please provide a minimal sample that shows the pivot issue?

**Comment by zubair1599** [comment]
Thanks @Luke for your help to identify issue make it work. Main issue was assignment of **this** variable in data attribute of pivot items in OnReady event. Once we assign it to temp variable and use temp variable in binding, it worked.  



<div id="mainPivot"> </div>

<script id="pivotItemLine0" type="text/html">
        <div id="transactionDetails">
            <div class="h4">Header 1</div>
            <p class="borderBottomThin"><h3  data-bind="text: bindingValue0"></h3></p>
        </div>
    </script>

    <script id="pivotItemLine1" type="text/html">
        <div id="lineDetails">
            <div class="h4">Header 2</div>
            <p class="borderBottomThin"><h3  data-bind="text: bindingValue1"></h3></p>
        </div>
    </script>

-----
//////TS File //////

    public pivot: IPivot;
    public tab1: IPivotItem;
    public tab2: IPivotItem;
    public bindingValue0: ko.Observable<string>;
    public bindingValue1: ko.Observable<string>;


public onReady(element: HTMLElement): void {
    
        let self = this;
        this.tab1 = {
            id: "pivotItemLine0",
            header: this.context.resources.getString("string_amct01"),
            onReady(element: HTMLElement) {
                ko.applyBindingsToNode(element, {
                    template: {
                        name: "pivotItemLine0",
                        data: self
                    }
                });
                
            },
            onShown() {
            }
        };
        this.tab2= {
            id: "pivotItemLine1",
            header: this.context.resources.getString("string_amct02"),
            onReady(element: HTMLElement) {
                ko.applyBindingsToNode(element, {
                    template: {
                        name: "pivotItemLine1",
                        data: self
                    }
                });

                //element.append(pivotTransElement);
            },
            onShown() {
            }
        };

        let pivotItems: IPivotItem[] = [this.line, this.transaction];

        let pivotOptions: IPivotOptions = {
            items: pivotItems
        };
        
        let pivotRootElement: HTMLDivElement = element.querySelector("#mainPivot") as HTMLDivElement;
        this.pivot = this.context.controlFactory.create(this.context.logger.getNewCorrelationId(), "Pivot", pivotOptions, pivotRootElement);
        this.pivot.addEventListener("SelectionChanged", (eventData: { selectedItem: IPivotItem }) => {
            this.pivotItemSelectionHandler(eventData.selectedItem);
        });

        ko.applyBindings(this, element);
    }
