### ISSUE TITLE
Knockout Bindings issue when executing installers without activating the Store Commerce App

### ISSUE THREAD

**Issue by zubair1599** [microsoft/Dynamics365Commerce.InStore#25]
Hi PG,
During the installation, we found one issue. When we install the Store Commerce App(Base installer) and custom installer and further activate the store commerce app, the bindings not working. If custom installer is installed after the base app **Activation**, then everything works fine. Does the order of installation matters?

Following steps we noticed. 
Not Working

1. Install Store Commerce App Base installer.
2. Install Custom installer.
3. Activate the Store Commerce App
4. Start App. Bindings has issues

Working
1. Install Store Commerce App Base installer.
2. Activate the Store Commerce App
3. Install Custom installer.
4. Start App. Worked!

Thanks
Zubair

**Comment by lukedgr** [comment]
Hi @zubair1599 , are you using the application start trigger to register your knockout bindings? If so, that is likely the cause of the issue. Please also register the bindings in a PostDeviceActivationTrigger
