### ISSUE TITLE
Telemetry for store commerce

### ISSUE THREAD

**Issue by chmasade** [microsoft/Dynamics365Commerce.InStore#27]
Hello everyone,

Good Day!!!

We are migrating Retail SDK to Store Commerce, and having query below

Request your help here...

Can we use telemetry in store commerce as we use in Retail SDK(POS).
Telemetry:
We are trying to log the information and customization errors in AppInsight of Azure. We are following the link as provided by MS [Log extension events to Application Insights - Commerce | Dynamics 365 | Microsoft Learn](https://learn.microsoft.com/en-us/dynamics365/commerce/dev-itpro/commerce-application-insights)
We are facing issue as we are not able to build the project and getting the configuration error in tsconfig.json file after installation of npm module.

Thanks,
Chaya Masade

**Comment by lukedgr** [comment]
Hi @chmasade , could you please share a link to a project that has a minimal repro of the issue? Also, sharing more details about your TSConfig and the errors that you are getting will be needed to help troubleshoot. Thanks.

**Comment by chmasade** [comment]
Hi Luke,

We are setting up the telemetry log in POS project for commerce SDK. We have installed NPM in the same project as written in the MS document an done with some changes in config files.
As a next step, we build the project but ending up with the below errors for all JS files which will be installed during NPM installation:

(TS) File 'K:/RSDKToCSDK/CommerceSDK/POS/Libraries/node_modules/@microsoft/applicationinsights-analytics-js/src/JavaScriptSDK/ApplicationInsights.ts' is not under 'rootDir' 'K:/RSDKToCSDK/CommerceSDK/POS/Libraries/node_modules/@microsoft/applicationinsights-analytics-js/extensions/applicationinsights-analytics-js/src'. 'rootDir' is expected to contain all source files.

Please find the snippet for TSconfig file:

<img width="692" alt="image" src="https://user-images.githubusercontent.com/114393573/195522914-629cbd22-ac37-4a1f-9c21-56329334e2f9.png">


<img width="551" alt="image" src="https://user-images.githubusercontent.com/114393573/195522645-396cf1d8-31bc-41fc-98ef-10463c547340.png">

<img width="310" alt="image" src="https://user-images.githubusercontent.com/114393573/195523261-12e79998-aca3-4666-bb8f-bd51e9e4ea20.png">


Thanks in advance,
Chaya Masade

**Comment by JeriCode** [comment]
Is there any update?

**Comment by lukedgr** [comment]
Hi @chmasade and @JeriCode , please try updating your project so that only the javascript files from the application insights node modules are included in the project root directory. Otherwise, the typescript compiler will try to compile the node_modules again which causes problems.

**Comment by chmasade** [comment]
Hi @lukedgr , 

we will try this and update you.

Thanks,
Chaya

**Comment by chmasade** [comment]
Hi @lukedgr,

We tried the solution to exclude the TS files, as we are referencing only the applicationinsights-web folder. Still the issue persists. Please find the attached snippet for the error.

<img width="719" alt="image" src="https://user-images.githubusercontent.com/114393573/196942992-736eb966-2152-4f39-86d9-d1302e0cce76.png">

<img width="935" alt="image" src="https://user-images.githubusercontent.com/114393573/196943282-bd40ec69-ea31-4b0a-992f-f97b81d875b6.png">

Thanks,
Chaya Masade

**Comment by lukedgr** [comment]
@chmasade , I was able to get this working in my own sample this afternoon. Please refer to the commit linked below to see how to include application insights in your POS extension package.

https://github.com/microsoft/Dynamics365Commerce.InStore/commit/a901bc4b5b8f6422f07070d72d8160eb3f293eec
