### ISSUE TITLE
how to avoid hardcoding the package name in defineposextension trigger in store commerce

### ISSUE THREAD

**Issue by chmasade** [microsoft/Dynamics365Commerce.InStore#28]
Hello everyone,

Good Day!!!

We are migrating Retail SDK to Store Commerce, and having below query.

Request your help here...

Can we make the package name as dynamic not hardcoded, which is defined in POS extension package trigger.
Basically, we are mentioning the package name in the defineposextension trigger and the same name in the customization package props file. Is there possibility to make this as dynamic like a configuration in HQ?

Thanks,
Chaya Masade

**Comment by lukedgr** [comment]
Hi @chmasade , this should be possible using extension settings for CRT. You can specify the CRT extension settings in your ScaleUnit project like is shown in the link below.

https://github.com/microsoft/Dynamics365Commerce.InStore/blob/release/9.40/src/StoreCommerceSamples/Solutions/GasStationSample/ScaleUnit/Contoso.GasStationSample.ScaleUnit.csproj#:~:text=%3CCommerceRuntimeExtensionSettings%20Include%3D%22ext.Contoso.GasolineItemId%22%3E

Then in CRT in the trigger that is defining the extension package you can read the value like in the example below.

https://github.com/microsoft/Dynamics365Commerce.InStore/blob/69fd981977d791c9cdde877ab17e9d8ae489b650/src/StoreCommerceSamples/Solutions/GasStationSample/CommerceRuntime/GasPumpsDataService.cs#:~:text=request.RequestContext.Runtime.Configuration.Settings.TryGetValue(%22ext.Contoso.GasolineItemId%22

**Comment by chmasade** [comment]
Hi Luke:

The above solution will not work for us, as we don't want to not hardcode the package name value in the below snippet.
<img width="929" alt="image" src="https://user-images.githubusercontent.com/114393573/195254590-b16d96b7-8fe3-4585-97eb-d9c43174f93e.png">
we want to setup the package name in customizationpackage.props file dynamically. Where in the above solution is about the app settings keys.
<img width="737" alt="image" src="https://user-images.githubusercontent.com/114393573/195254770-d68d28fb-3d85-4478-b53b-c2ba0ccc3ea0.png">


Thanks,
Chaya Masade

**Comment by lukedgr** [comment]
@chmasade , you can use the $(PackageName) variable in the scale unit solution to specify the value for the setting. This would allow you to dynamically set the package name when building from the command line. I believe that should work based on the requirements above. If not, please provide more details on the specific business requirement you are trying to achieve. Thanks!

**Comment by chmasade** [comment]
Hi @lukedgr,

Can you help me with the steps in detail as how to use the $(PackageName) variable in scale unit solution.
How can we get it in runtime so that we will be able to set the value.

Thanks,
Chaya Masade
