### ISSUE TITLE
On- prem support for store commerce and mpos sealed

### ISSUE THREAD

**Issue by PionnersIT-Retail** [microsoft/Dynamics365Commerce.InStore#32]
is store commerce and rcsu supported on on prem deployement

**Comment by lukedgr** [comment]
@PionnersIT-Retail , Store Commerce and the Scale Unit can be deployed on prem. Please refer to this document for on prem scale unit deployments.

https://learn.microsoft.com/en-us/dynamics365/commerce/dev-itpro/retail-store-system-begin
