### ISSUE TITLE
How to enable/disable POS extensions with single installer strategy, since we have one manifest.json file

### ISSUE THREAD

**Issue by chmasade** [microsoft/Dynamics365Commerce.InStore#34]
Hi All,

we have a requirement in our project to implement country or region specific changes, but instead of having multiple installer/projects, how can we achieve this is in single installer:

<img width="494" alt="image" src="https://user-images.githubusercontent.com/114393573/203819477-a8814ab1-952e-4e99-bcaa-ab7b4d298b65.png">

**Comment by madyke** [comment]
Hi @chmasade - is there a business reason you don't want to have multiple installers? This would be perfect for independent packaging - having different installers for different countries/regions.
