### ISSUE TITLE
Config file for Store commerce app activation for SCCM based deployment

### ISSUE THREAD

**Issue by thanuja254** [microsoft/Dynamics365Commerce.InStore#35]
Hi everyone,
We are currently using config file from devices in HQ in our SCCM deployment to auto fill the activation page with Retail server URL and device details while installing the MPOS, so that we needn’t manually enter them and thus avoid any mistakes. We are trying to do something similar for our store commerce installation as well, however when we try to check for the config file on HQ for a device type of store commerce, we do not have a download option.
<img width="592" alt="1" src="https://user-images.githubusercontent.com/74947885/206241006-f9dbff79-cde4-49ff-8cd7-2c09e5366e73.png">
<img width="788" alt="2" src="https://user-images.githubusercontent.com/74947885/206241041-7ba2da3f-f5a4-48ac-b775-238f1d3fb05f.png">

Is there a way to get this file for store commerce. Any inputs are appreciated.

**Comment by madyke** [comment]
Hi @thanuja254 - Unfortunately this is not currently supported for Store Commerce. We are working on adding this feature in a future release (date TBD).

**Comment by thanuja254** [comment]
@madyke Thank you for the confirmation.
