### ISSUE TITLE
Issue with proxy manager in offline

### ISSUE THREAD

**Issue by vishnuvardhanreddy-kunduru** [microsoft/Dynamics365Commerce.InStore#37]
When we are trying to use store commerce offline mode, we are getting the below error from one of our custom controller.

****Commerce SDK version**: 9.40**

our custom entity:

<img width="401" alt="image" src="https://user-images.githubusercontent.com/122993581/213199568-ad462e22-bf98-4732-8c2d-0cc5d95382e3.png">

our controller:
<img width="416" alt="image" src="https://user-images.githubusercontent.com/122993581/213200000-1f3e32d4-a57e-4ba3-9182-b998fe4d92b3.png">

**please find the below error:**

Retail proxy client offline request failed. RequestUri: crt://offline/SalesChannelManager/UpdateEmployeeLastUsedOrderType?personnelNumber=SCRUBBED&orderTypeRecId=SCRUBBED&%24locale=SCRUBBED. Exception: System.InvalidOperationException: Can't find manager (SalesChannelManager) with method (UpdateEmployeeLastUsedOrderType) with parameter count (2)
   at Microsoft.Dynamics.Commerce.RetailProxy.Adapters.AdaptorCaller.<CallCommerceRuntimeAsync>d__29.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Commerce.RetailProxy.Adapters.AdaptorCaller.<ExecuteAsync>d__26.MoveNext().

**Comment by madyke** [comment]
Hello @vishnuvardhanreddy-kunduru - if Retail Proxy failed to find the manager/method combo, then most likely, the adaptor failed to set up properly.

There should be more logs and errors in the Event Viewer if this is the case, which will help point you to what is actually going wrong with the setup. You can check to see if there is an error such as `GenerateProxyManagerAdapterFailure`, which will have exception details about what went wrong with the adapter setup.

**Comment by Pikhulya** [comment]
@vishnuvardhanreddy-kunduru , can you please confirm you are unblocked by the recommendation Matt gave you?
