### ISSUE TITLE
Building POS Samples fails when signing the MPOS MSIX due to error "Export-PfxCertificate : Using ProtectTo parameter requires running as a domain account."

### ISSUE THREAD

**Issue by lukedgr** [microsoft/Dynamics365Commerce.InStore#4]
Attempting to build the POS sample fails during MPOS app package signing when running as a user that is not attached to a domain and a signing cert does not already exist. See error and screenshot below.

Error Message:
"Export-PfxCertificate : Using ProtectTo parameter requires running as a domain account."

Screenshot:
![DomainAccountError](https://user-images.githubusercontent.com/3270455/141135985-c21896d3-753b-4142-a46a-a3e960e429c7.png)

**Comment by lukedgr** [comment]
This issue is due to a known limitation with the powershell APIs for creating a signing certificate. If the user is not signed in using a domain account we're not able to automatically generate the signing certificate for the MPOS solution due to a limitation with the [Export-PfxCertificate](https://docs.microsoft.com/en-us/powershell/module/pki/export-pfxcertificate?view=windowsserver2019-ps#parameters) powershell command and the ProtectTo option. To resolve this issue please follow these steps below to create a test certificate and for more details on app signing please refer to [this article](https://docs.microsoft.com/en-us/dynamics365/commerce/dev-itpro/pos-extension/mpos-extension-signing).

1. Follow the steps in [this article](https://docs.microsoft.com/en-us/windows/win32/appxpkg/how-to-create-a-package-signing-certificate) to create a test certificate for package signing.
  - Note: The publisherName for the certificate should match the "PackagePublisher" specified in the solution's CustomizationPackage.props file.
2. Copy the created certificate to the ModernPOS project folder
3. Update the ModernPos packaging project (jsproj) to reference the new test certificate by updating the "[PackageCertificateKeyFile](https://github.com/microsoft/Dynamics365Commerce.InStore/blob/release/9.33/src/PosSample/ModernPos/ModernPos.jsproj#L30)"
4. Build & run the solution

**Comment by fcaminada** [comment]
For future reference, the PFX file used to sign the ModernPOS package cannot be password-protected. To create PFX without a password the following commands can be used:

**When exporting directly from the store using the thumbprint:** ([reference](https://github.com/MicrosoftDocs/windows-uwp/issues/1836#issuecomment-538692042))
Export-PfxCertificate -cert "Cert:\CurrentUser\My\<Certificate Thumbprint>" -FilePath <FilePath>.pfx -Password (new-object System.Security.SecureString)
The command must be run from a PowerShell command prompt.

**When exporting from .cer and .pvk files:**
Pvk2Pfx /pvk <PvkFilePath>.pvk /pi <Private Key Password> /spc <CerFilePath>.cer /pfx <PfxFilePath>.pfx /po ""
If the private key doesn't have a password /pi and /po can be omitted.
