### ISSUE TITLE
How to copy files part of hardware station extension

### ISSUE THREAD

**Issue by Suhail-Ismail** [microsoft/Dynamics365Commerce.InStore#7]

**Comment by Suhail-Ismail** [comment]
@Pikhulya In Retail SDK, we can specify the non dll files that has to be copied to EXT folders in the customization.settings file. I wanted to know how we can do the same using the new Extension development method. 

Currently i have some html files which are part of the hardware extension. I am not sure how to make that file part of the installation package.

**Comment by Pikhulya** [comment]
Those files need to be included as resources into one of the assemblies composing your extensions so the files could then be accessed by your code once it extracts them from resources.
